matrix:
  matrix:
  include:
    - os: osx
      osx_image: xcode9.2
    - os: linux
      dist: trusty
      sudo: required
env:
  global:
  - FTP_USER=u67889354-benjamin
  
after_success:
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    cd /home/travis/build/benkuper/LaMoucheFolle/Builds/LinuxMakefile/build
    zip LaMoucheFolle-linux-x64-bleedingedge.zip LaMoucheFolle
    curl --ftp-create-dirs -T LaMoucheFolle-linux-x64-bleedingedge.zip -u $FTP_USER:$FTP_PASSWORD ftp://ftp.kuperberg.fr/lamouchefolle/download
  else
    cd /Users/travis/build/benkuper/LaMoucheFolle/Builds/MacOSX/build/Release
    ls
    zip -r -y LaMoucheFolle-osx-bleedingedge.zip LaMoucheFolle.app
    curl --ftp-create-dirs -T LaMoucheFolle-osx-bleedingedge.zip -u $FTP_USER:$FTP_PASSWORD ftp://ftp.kuperberg.fr/lamouchefolle/download
  fi
language: cpp
git:
  depth: 1
notifications:
  email: false
before_install:
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    export DEBIAN_FRONTEND=noninteractive
    echo ${HOME}
    export HOME=/home/travis/build/benkuper
    echo ${HOME}
    sudo add-apt-repository ppa:webkit-team/ppa -y
    sudo apt-get update --fix-missing
    sudo apt-get update -qq
    sudo apt-get install -qq clang libfreetype6-dev libx11-dev libxinerama-dev libxrandr-dev libxcursor-dev libxcomposite-dev mesa-common-dev libasound2-dev freeglut3-dev libcurl4-gnutls-dev+ libasound2-dev libjack-dev libbluetooth-dev libgtk-3-dev libwebkit2gtk-4.0-dev
    sudo apt-get install -qq libusb-1.0-0-dev
    pwd
    ls -d */
    cd ..
    pwd
    git clone --depth=1 --branch=master https://github.com/WeAreROLI/JUCE.git JUCE
    mkdir "JUCE Modules"
    cd "JUCE Modules"
    git clone --depth=1 --branch=master https://github.com/benkuper/juce_organicui.git juce_organicui
    cd ..
    pwd
    ls -d */
  else
    brew update
    brew install libusb
    gem install xcpretty
    gem install xcpretty-travis-formatter
    pwd
    ls -d */
    cd /Users/travis
    git clone --depth=1 --branch=master https://github.com/WeAreROLI/JUCE.git JUCE
    cd /Users/travis/build/benkuper
    mkdir "JUCE Modules"
    cd "JUCE Modules"
    git clone --depth=1 --branch=master https://github.com/benkuper/juce_organicui.git juce_organicui
    cd ..
    pwd
    ls -d */
  fi
compiler:
- clang
branches:
  only:
  - master
script:
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    make -j 8 CONFIG=Release -C "LaMoucheFolle/Builds/LinuxMakefile/"
  else
    xcodebuild -project LaMoucheFolle/Builds/MacOSX/LaMoucheFolle.xcodeproj -configuration Release -jobs 8 | xcpretty -f `xcpretty-travis-formatter`
  fi